config/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.contrib.staticfiles.urls import static
from django.views.generic.base import RedirectView

from .settings import settings


urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('qa:questions'), permanent=True)),
    path('questions/', include('hasker.qa.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('hasker.users.urls')),
    path('api/', include('hasker.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hasker/qa/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "qa"
urlpatterns = [
    path('', views.IndexView.as_view(), name='questions'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('ask/', login_required(views.AddQuestionView.as_view(),
                                login_url='users:login'), name='ask'),
    path('update', views.update_votes, name='update'),
    path('<int:pk>/', views.QA_DetailView.as_view(), name='detail'),
    path('tags/<int:pk>/', views.TaggedView.as_view(), name='tag'),
    path('trending', views.TrendingView.as_view(), name='trending'),
    path('accept', views.accept_answer, name='accept'),
]

hasker/qa/models.py
from datetime import datetime
import pytz

from django.utils import timezone
from django.db import models, transaction
from django.conf import settings
from django.urls import reverse

from hasker.qa.utils.helper import *


class QA(models.Model):
    body = models.TextField(verbose_name='Text')
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    date = models.DateTimeField()
    title = None

    class Meta:
        abstract = True

    def get_tags(self):
        return None

    def counts_likes(self):
        return str(self.u_likes.count())

    def counts_dislikes(self):
        return str(self.u_dislikes.count())

    def hate_this(self, user, hate=True):
        with transaction.atomic():
            if hate:
                self.u_likes.remove(user)
                change_hate = self.u_dislikes
            else:
                self.u_dislikes.remove(user)
                change_hate = self.u_likes
            if change_hate.filter(pk=user.id).exists():
                change_hate.remove(user)
            else:
                change_hate.add(user)
        return self.u_likes.count() - self.u_dislikes.count()


class Tag(models.Model):
    name = models.CharField(max_length=32, unique=True)


class Answer(QA):
    u_likes = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                     related_name='answer_likes_set',
                                     blank=True)
    u_dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='answer_dislikes_set',
                                        blank=True)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)

    def save_new_answer(self, author, question_pk, body):
        with transaction.atomic():
            q = Question.objects.get(pk=question_pk)
            self.date = datetime.now(pytz.timezone(settings.TIME_ZONE))
            self.author = author
            self.question = q
            self.save()
            q.answers.add(self)
            new_answer_notify(q.author.email, reverse('qa:detail', args=[question_pk]))

    def accept(self, question_author):
        with transaction.atomic():
            q = self.question
            if q.author != question_author or self not in q.answers.all():
                raise ValueError("Invalid value")
            if q.accepted_answer == self:
                q.accepted_answer = None
                q.save()
                return
            q.accepted_answer = self
            q.save()
            return True


class Question(QA):
    TAGS_NUM = 3

    title = models.CharField(max_length=255, verbose_name='Title')
    tags = models.ManyToManyField(Tag, blank=True)
    accepted_answer = models.ForeignKey(Answer, on_delete=models.CASCADE,
                                        related_name='accepted_answer',
                                        blank=True, null=True)
    answers = models.ManyToManyField(Answer, related_name='question_answers_set',
                                     blank=True)
    u_likes = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                     related_name='question_likes_set',
                                     blank=True)
    u_dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='question_dislikes_set',
                                        blank=True)

    def show_tags(self):
        return list(self.tags.values_list('name', flat=True))

    def get_tags(self):
        return self.tags.all()

    def save_new_question(self, author, tag_list):
        with transaction.atomic():
            self.date = datetime.now(pytz.timezone(settings.TIME_ZONE))
            self.author = author
            self.save()
            for t in tag_list:
                self.tags.add(Tag.objects.get_or_create(name=t)[0])

hasker/qa/forms.py
from string import Template
from datetime import datetime

from django import forms

from .models import Question, Tag, Answer


class AddQuestionForm(forms.ModelForm):
    header_title = "Ask a question"
    submit_title = "Save"
    field_order = ['title', 'body', 'form_tags']
    form_tags = forms.CharField(required=True, label='Tags')

    class Meta:
        model = Question
        fields = ['title', 'body']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_form_tags(self):
        tags = self.cleaned_data['form_tags'].lower()
        tags = [t.strip() for t in tags.split(",") if t.strip()]
        max_tag_length = Tag._meta.get_field('name').max_length
        if len(tags) > Question.TAGS_NUM:
            raise forms.ValidationError('Number of tags must be less than: %(len)s',
                                        code='invalid',
                                        params={'len': Question.TAGS_NUM},
                                        )
        for t in tags:
            if len(t) > max_tag_length:
                raise forms.ValidationError("Tag's length must be: %(len)s",
                                            code='invalid',
                                            params={'len': max_tag_length},
                                            )
        return tags

    def save(self, author, commit=True):
        question = super().save(commit=False)
        question.save_new_question(author, self.cleaned_data['form_tags'])


class AddAnswerForm(forms.ModelForm):
    header_title = "Your answer"
    submit_title = "Submit"

    class Meta:
        model = Answer
        fields = ['body']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['body'].label = ""

    def save(self, author, question_pk, commit=True):
        answer = super().save(commit=False)
        answer.save_new_answer(author, question_pk, self.cleaned_data['body'])

hasker/qa/views.py
import logging

from django import forms
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.db.models import Count, F, Q
from django.views.decorators.http import require_http_methods
from django.http import JsonResponse
from django.conf import settings

from hasker.qa.utils.helper import *
from .models import Question, Answer, Tag
from .forms import AddQuestionForm, AddAnswerForm

logger = logging.getLogger(__name__)


class IndexView(generic.ListView):
    template_name = 'qa/home.html'
    paginate_by = settings.QUESTION_PAGINATE
    context_object_name = 'question_list'
    sort = {'new': ['-date', '-votes'], 'hot': ['-votes', '-date']}
    default_sort = 'new'
    search_string = ""
    title = ""

    def set_sort(self, queryset):
        value = self.request.GET.get('tab', self.default_sort)
        return queryset.order_by(*self.sort[value])

    def set_filter(self, queryset):
        return queryset

    def build_queryset(self):
        return Question.objects\
                       .prefetch_related('tags')\
                       .select_related('author')\
                       .annotate(Count('answers', distinct=True),
                                 Count('u_likes', distinct=True),
                                 Count('u_dislikes', distinct=True))\
                       .annotate(votes=F('u_likes__count') - F('u_dislikes__count'))

    def get_queryset(self):
        qs = self.build_queryset()
        qs = self.set_filter(qs)
        qs = self.set_sort(qs)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_string'] = self.search_string
        context['title'] = self.title
        return context


class SearchView(IndexView):
    default_sort = 'hot'
    title = "Search result"

    def set_filter(self, queryset):
        search_string = self.request.GET.get('find', "")
        tag_names, find_value = parse_search_string(search_string)
        self.search_string = search_string
        if find_value:
            queryset = queryset.filter(Q(title__contains=find_value) |
                                       Q(body__contains=find_value))
        queryset = set_filter_by_tag_names(queryset, tag_names)
        return queryset


class TaggedView(IndexView):
    default_sort = 'hot'
    title = "Tag result"

    def set_filter(self, queryset):
        tag_pk = self.kwargs.get('pk')
        tag = get_object_or_404(Tag, pk=tag_pk)
        self.search_string = "tag:{}".format(tag.name)
        queryset = queryset.filter(tags__id=tag_pk)
        return queryset


class AddQuestionView(generic.View):
    template_name = 'users/signup.html'
    form_class = AddQuestionForm
    ctx_obj_name = 'form'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {self.ctx_obj_name: self.form_class})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save(request.user)
            return redirect(reverse('qa:questions'))
        return render(request, self.template_name, {self.ctx_obj_name: form})


class TrendingView(generic.ListView):
    template_name = 'include/trending.html'
    context_object_name = 'question_list'

    def get_queryset(self):
        return Question.objects.order_by('-votes', '-date')\
                       .annotate(Count('u_likes', distinct=True),
                                 Count('u_dislikes', distinct=True))\
                       .annotate(votes=F('u_likes__count') -
                                 F('u_dislikes__count'))[:settings.TRENDING_NUM]


class QA_DetailView(generic.ListView):
    template_name = 'qa/qa_detail.html'
    form_class = AddAnswerForm
    context_object_name = 'items'
    paginate_by = settings.ANSWER_PAGINATE

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.answer_form = self.form_class()

    def get_queryset(self):
        question_pk = self.kwargs.get('pk')
        q = get_object_or_404(Question, pk=question_pk)
        return q.answers.all()\
                .annotate(Count('u_likes', distinct=True),
                          Count('u_dislikes', distinct=True))\
                .annotate(votes=F('u_likes__count') -
                          F('u_dislikes__count'))\
                .order_by('-date')\
                .select_related('author')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question_pk = self.kwargs.get('pk')

        context['question'] = Question.objects\
                                      .annotate(Count('u_likes', distinct=True),
                                                Count('u_dislikes', distinct=True))\
                                      .annotate(votes=F('u_likes__count') -
                                                F('u_dislikes__count'))\
                                      .get(pk=question_pk)
        context['form'] = self.answer_form
        return context

    def get(self, request, *args, **kwargs):
        self.answer_form = self.form_class()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse('user:login'))
        question_pk = kwargs.get('pk')
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save(request.user, question_pk)
            return redirect(reverse('qa:detail', args=[question_pk]))
        return super().get(request, *args, **kwargs)


@require_http_methods(["POST"])
def update_votes(request):
    if not request.user.is_authenticated:
        return JsonResponse({'status': 'FAIL'})
    item_id = request.POST.get('id')
    item_value = request.POST.get('value')
    item_type = request.POST.get('type')
    try:
        if item_type == 'question':
            obj = Question.objects.get(pk=item_id)
        elif item_type == 'answer':
            obj = Answer.objects.get(pk=item_id)
        else:
            raise ValueError("Wrong update")
        if item_value == "hate":
            votes = obj.hate_this(request.user)
        elif item_value == "love":
            votes = obj.hate_this(request.user, False)
        else:
            raise ValueError("Wrong update")
    except Exception as e:
        logger.error('update_votes failed: {} {} {}'.format(item_id, item_value, item_type))
        return JsonResponse({'status': 'FAIL'})
    return JsonResponse({'status': 'OK', 'votes': votes},
                        json_dumps_params={'sort_keys': True})


@require_http_methods(["POST"])
def accept_answer(request):
    if not request.user.is_authenticated:
        return JsonResponse({'status': 'FAIL'})
    item_id = request.POST.get('id')
    item_value = request.POST.get('value')
    try:
        obj = Answer.objects.get(pk=item_id)
        result = obj.accept(request.user)
    except Exception as e:
        logger.error('accept_answer failed: {} {}'.format(item_id, item_value))
        return JsonResponse({'status': 'FAIL'})
    return JsonResponse({'status': 'OK', "accepted": result},
                        json_dumps_params={'sort_keys': True})

hasker/qa/templates/include/pagination.html
{% load custom_tags %}
{% if is_paginated %}
    <div class="container">
        <div class="row justify-content-center">
            {% if page_obj.has_previous %}
              <a class="reload_content" href="?{% http_get_param_replace page=page_obj.previous_page_number %}">prev</a>
            {% endif %}
              <p>&nbsp;{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}&nbsp;</p>
            {% if page_obj.has_next %}
              <a class="reload_content" href="?{% http_get_param_replace page=page_obj.next_page_number %}">next</a>
            {% endif %}
        </div>    
    </div> 
{% endif %} 

hasker/qa/templates/include/qa_item.html
<div class="row">
    <div class="col col-lg-2 align-self-center">
        <div class="row">
            <a type="button" class="votingButton btn btn-success btn-sm" item_id="{{ item.id }}"item_value = "love" item_type = "{{ qa_type }}" href="{% url 'qa:update' %}">love</a>
<!--             <form id="form_id" action="{% url 'qa:update' %}" change_item="{{ qa_type }}_{{ item.id }}">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ item.id }}" />
                <input type="hidden" name="value" value="love" />
                <input type="hidden" name="type" value="{{ qa_type }}" />
                <a type="button" class="btn btn-success btn-sm">love</a>
            </form> -->
        </div>
        <div class="row">
            <h2 id="{{ qa_type }}_{{ item.id }}">{{ item.votes }}</h2>
        </div>
        <div class="row">
            <a type="button" class="votingButton btn btn-danger btn-sm" item_id="{{ item.id }}" item_value = "hate" item_type = "{{ qa_type }}" href="{% url 'qa:update' %}">hate</a>
        </div>
        {% if qa_type == "answer" %}
        <div class="row" id="accepted_{{ item.id }}">
            {% if user == item.question.author %}
                {% if item.question.accepted_answer == item %}
                    <a class="acceptAnswer text-muted" id="{{ item.id }}" href="{% url 'qa:accept' %}">accepted !</a>
                {% else %}
                    <a class="acceptAnswer text-muted" id="{{ item.id }}" href="{% url 'qa:accept' %}">accept</a>
                {% endif %}
            {% else %}
                {% if item.question.accepted_answer == item %}
                    accepted
                {% endif %}
            {% endif %}
        </div>
        {% endif %}
    </div>
    <div class="col">
        {% if item.title %}
        <div class="row justify-content-center">
            {{ item.title }}
        </div>
        {% endif %}
        <div class="row">
            {{ item.body }}
        </div>
        <div class="row">
            {% if item.get_tags %}
            <div class="col col text-right">
                {% for tag in item.get_tags %}
                    <a type="button" class="btn btn-primary btn-sm mr-1" href="{% url 'qa:tag' tag.id %}">{{ tag.name }}</a>
                {% endfor %}
            </div>
            {% endif %}
        <div class="col col text-right">
            {% if item.author.avatar %}
                <img src="{{ item.author.avatar.url }}" width="60" alt="Oops ..." />
            {% endif %}
            {{ item.author }}
        </div>
        </div>
    </div>
</div>
<hr>

hasker/qa/templates/include/questions_list.html
<div class="row">
    <div class="container">
    {% for question in question_list %}
        {% include "include/show_question.html" %}
    {% empty %}
        <div class="row justify-content-center">
            <h2>No questions are available</h2>
        </div>    
    {% endfor %}
    </div>
</div>
<div class="row">
    {% include "include/pagination.html" %}
</div>

hasker/qa/templates/include/show_question.html
{% load humanize %}
<div class="row">
    <div class="col-lg-2">
        <div class="row justify-content-center">{{ question.votes }}</div>
        <div class="row justify-content-center">Votes</div>
    </div>
    <div class="col-lg-2">
        <div class="row justify-content-center">{{ question.answers__count }}</div>
        <div class="row justify-content-center">Answers</div>
    </div>
    <div class="col">
        <div class="row justify-content-center">
            <a href="{% url 'qa:detail' question.id %}">{{ question.title }}</a>  
        </div>  
        <div class="row justify-content-center">
            <div class="btn-toolbar">
            {% for tag in question.get_tags %}
                <a type="button" class="btn btn-primary btn-sm mr-1" href="{% url 'qa:tag' tag.id %}">{{ tag.name }}</a>
            {% endfor %} 
            </div>
        </div> 
    </div>
    <div class="col-lg-2">
        <div class="row justify-content-center">
            {% if question.author.avatar %}
                <a href="{{ question.author.avatar.url }}">{{ question.author }}</a>
            {% else %}
                {{ question.author }}
            {% endif %}
            
        </div>
        <div class="row justify-content-center text-center">
            {{ question.date | naturaltime }}
        </div> 
    </div>
</div>
<hr class="half-rule"/>

hasker/qa/templates/include/trending.html
<div class="container">
    <div class="row justify-content-center">
        <h2>Trending</h2>
    </div>
    {% for question in question_list %}
    <div class="row">
        <div class="col">
            {{ question.votes }}
        </div>
        <div class="col">
            <a href="{% url 'qa:detail' question.id %}">{{ question.title }}</a>
        </div>
    </div>
    {% empty %}
        <div>No questions</div>
    {% endfor %}
</div>
    